In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import time

In [2]:
df=pd.read_csv("F:\Work\diease detection\chronic-1.csv")

In [3]:
df=df.replace('?',np.nan)

In [4]:
#data=df[['sg','al','su','bgr','bu','sc','pot','hemo','pcv','rbcc','rbc','htn','dm','appet','Label']].copy()

In [5]:
#df1=df.drop(columns=['id','age','bp','sg','al','su','bgr','bu','sc','sod','pot','hemo','pcv','wbcc','rbcc'])

In [6]:
df

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane,Label
0,1,48,80,1.02,1,0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,2,7,50,1.02,4,0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,294,50,NaN,1.02,0,0,normal,normal,notpresent,notpresent,...,48,4700,5.4,no,no,no,good,no,no,notckd
3,3,62,80,1.01,2,3,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
4,4,48,70,1.005,4,0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,258,38,60,1.02,0,0,normal,normal,notpresent,notpresent,...,46,9100,5.8,no,no,no,good,no,no,notckd
396,245,64,90,1.015,3,2,NaN,abnormal,present,notpresent,...,40,9800,4.6,yes,yes,no,good,no,yes,ckd
397,246,48,100,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,...,19,7200,2.6,yes,no,yes,poor,no,no,ckd
398,247,48,110,1.015,3,0,abnormal,normal,present,notpresent,...,26,5000,2.5,yes,no,yes,good,no,yes,ckd
399,325,40,80,1.02,0,0,normal,normal,notpresent,notpresent,...,NaN,NaN,NaN,no,no,no,good,no,no,notckd

In [7]:
df1=df.drop(columns=['id','rbc','pc','pcc','ba','htn','dm','cad','appet','pe','ane','Label'])

In [8]:
df1

    age   bp     sg   al   su  bgr   bu    sc  sod  pot  hemo  pcv  wbcc rbcc
0    48   80   1.02    1    0  121   36   1.2  NaN  NaN  15.4   44  7800  5.2
1     7   50   1.02    4    0  NaN   18   0.8  NaN  NaN  11.3   38  6000  NaN
2    50  NaN   1.02    0    0   92   19   1.2  150  4.8  14.9   48  4700  5.4
3    62   80   1.01    2    3  423   53   1.8  NaN  NaN   9.6   31  7500  NaN
4    48   70  1.005    4    0  117   56   3.8  111  2.5  11.2   32  6700  3.9
..   ..  ...    ...  ...  ...  ...  ...   ...  ...  ...   ...  ...   ...  ...
395  38   60   1.02    0    0   91   36   0.7  135  3.7    14   46  9100  5.8
396  64   90  1.015    3    2  463   64   2.8  135  4.1  12.2   40  9800  4.6
397  48  100    NaN  NaN  NaN  103   79   5.3  135  6.3   6.3   19  7200  2.6
398  48  110  1.015    3    0  106  215  15.2  120  5.7   8.6   26  5000  2.5
399  40   80   1.02    0    0  119   15   0.7  150  4.9   NaN  NaN   NaN  NaN

[400 rows x 14 columns]

In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [10]:
lr=LinearRegression()
imp=IterativeImputer(estimator=lr,verbose=2,max_iter=100, tol=1e-10, imputation_order='roman')

In [11]:
df2=imp.fit_transform(df1)

[IterativeImputer] Completing matrix with shape (400, 14)
[IterativeImputer] Ending imputation round 1/100, elapsed time 0.35
[IterativeImputer] Change: 5240.18969198514, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 2/100, elapsed time 0.41
[IterativeImputer] Change: 653.8287601606843, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 3/100, elapsed time 0.45
[IterativeImputer] Change: 363.8180722043091, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 4/100, elapsed time 0.49
[IterativeImputer] Change: 167.7693491853986, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 5/100, elapsed time 0.53
[IterativeImputer] Change: 89.20450997791129, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 6/100, elapsed time 0.56
[IterativeImputer] Change: 63.27932177052491, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 7/100, elapsed time 0.59
[IterativeImputer] Change: 48.84943002963345, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 8/100, elapsed time 0.61
[IterativeImputer] Change: 37.893134424975, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 9/100, elapsed time 0.64
[IterativeImputer] Change: 29.49078420262272, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 10/100, elapsed time 0.66
[IterativeImputer] Change: 23.007310842581628, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 11/100, elapsed time 0.68
[IterativeImputer] Change: 17.982996902103537, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 12/100, elapsed time 0.71
[IterativeImputer] Change: 14.076998062102911, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 13/100, elapsed time 0.74
[IterativeImputer] Change: 11.032793677083475, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 14/100, elapsed time 0.78
[IterativeImputer] Change: 8.655467622689205, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 15/100, elapsed time 0.81
[IterativeImputer] Change: 6.795892200108431, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 16/100, elapsed time 0.83
[IterativeImputer] Change: 5.339364824035842, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 17/100, elapsed time 0.87
[IterativeImputer] Change: 4.1972824238478275, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 18/100, elapsed time 0.90
[IterativeImputer] Change: 3.300960939950412, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 19/100, elapsed time 0.93
[IterativeImputer] Change: 2.5970017681177295, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 20/100, elapsed time 0.98
[IterativeImputer] Change: 2.0437899529192967, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 21/100, elapsed time 1.02
[IterativeImputer] Change: 1.6088296060931409, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 22/100, elapsed time 1.05
[IterativeImputer] Change: 1.266704484089265, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 23/100, elapsed time 1.09
[IterativeImputer] Change: 0.9975093074189396, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 24/100, elapsed time 1.12
[IterativeImputer] Change: 0.7856379169028092, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 25/100, elapsed time 1.16
[IterativeImputer] Change: 0.6188439839192637, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 26/100, elapsed time 1.19
[IterativeImputer] Change: 0.48751069527201807, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 27/100, elapsed time 1.22
[IterativeImputer] Change: 0.38408164092074193, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 28/100, elapsed time 1.25
[IterativeImputer] Change: 0.3111827970933184, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 29/100, elapsed time 1.27
[IterativeImputer] Change: 0.2558468135241757, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 30/100, elapsed time 1.30
[IterativeImputer] Change: 0.2102723934762477, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 31/100, elapsed time 1.33
[IterativeImputer] Change: 0.17275814818965018, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 32/100, elapsed time 1.36
[IterativeImputer] Change: 0.14189408247543345, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 33/100, elapsed time 1.38
[IterativeImputer] Change: 0.11651288403827387, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 34/100, elapsed time 1.40
[IterativeImputer] Change: 0.09564914681419734, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 35/100, elapsed time 1.43
[IterativeImputer] Change: 0.07850518237017812, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 36/100, elapsed time 1.45
[IterativeImputer] Change: 0.06442243946069381, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 37/100, elapsed time 1.48
[IterativeImputer] Change: 0.052857704251847215, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 38/100, elapsed time 1.51
[IterativeImputer] Change: 0.04336322633938572, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 39/100, elapsed time 1.53
[IterativeImputer] Change: 0.03557015035267519, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 40/100, elapsed time 1.56
[IterativeImputer] Change: 0.029174875187591764, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 41/100, elapsed time 1.59
[IterativeImputer] Change: 0.02392756135256191, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 42/100, elapsed time 1.61
[IterativeImputer] Change: 0.01962278721392563, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 43/100, elapsed time 1.63
[IterativeImputer] Change: 0.01609170054265152, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 44/100, elapsed time 1.66
[IterativeImputer] Change: 0.01319553815344554, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 45/100, elapsed time 1.69
[IterativeImputer] Change: 0.01082034409991317, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 46/100, elapsed time 1.71
[IterativeImputer] Change: 0.008872537427025318, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 47/100, elapsed time 1.74
[IterativeImputer] Change: 0.007275312939401535, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 48/100, elapsed time 1.77
[IterativeImputer] Change: 0.005965611396653969, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 49/100, elapsed time 1.80
[IterativeImputer] Change: 0.004891720901415764, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 50/100, elapsed time 1.82
[IterativeImputer] Change: 0.0040111921778390736, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 51/100, elapsed time 1.85
[IterativeImputer] Change: 0.0032892275259426285, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 52/100, elapsed time 1.87
[IterativeImputer] Change: 0.0026972642841446293, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 53/100, elapsed time 1.90
[IterativeImputer] Change: 0.002211894466763842, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 54/100, elapsed time 1.92
[IterativeImputer] Change: 0.001813921838393684, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 55/100, elapsed time 1.95
[IterativeImputer] Change: 0.0014875910991194452, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 56/100, elapsed time 1.98
[IterativeImputer] Change: 0.0012200281448516703, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 57/100, elapsed time 2.00
[IterativeImputer] Change: 0.0010006185689602765, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 58/100, elapsed time 2.03
[IterativeImputer] Change: 0.000820695107466296, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 59/100, elapsed time 2.06
[IterativeImputer] Change: 0.0006731559304123946, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 60/100, elapsed time 2.09
[IterativeImputer] Change: 0.0005521703031410308, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 61/100, elapsed time 2.11

[IterativeImputer] Change: 0.00045293479430286165, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 62/100, elapsed time 2.14
[IterativeImputer] Change: 0.00037155186889170633, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 63/100, elapsed time 2.17
[IterativeImputer] Change: 0.00030481566554607653, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 64/100, elapsed time 2.19
[IterativeImputer] Change: 0.00025006776150937604, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 65/100, elapsed time 2.22
[IterativeImputer] Change: 0.00020516559627670183, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 66/100, elapsed time 2.24
[IterativeImputer] Change: 0.0001683324729477853, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 67/100, elapsed time 2.26
[IterativeImputer] Change: 0.00013812036235361091, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 68/100, elapsed time 2.29
[IterativeImputer] Change: 0.00011332896223936739, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 69/100, elapsed time 2.31
[IterativeImputer] Change: 9.299710673138506e-05, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 70/100, elapsed time 2.33
[IterativeImputer] Change: 7.631204355096344e-05, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 71/100, elapsed time 2.36
[IterativeImputer] Change: 6.263113853333113e-05, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 72/100, elapsed time 2.39
[IterativeImputer] Change: 5.139874953907775e-05, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 73/100, elapsed time 2.42
[IterativeImputer] Change: 4.218462438443371e-05, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 74/100, elapsed time 2.45
[IterativeImputer] Change: 3.462490203831603e-05, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 75/100, elapsed time 2.47
[IterativeImputer] Change: 2.8419649700794913e-05, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 76/100, elapsed time 2.50
[IterativeImputer] Change: 2.332828912343654e-05, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 77/100, elapsed time 2.53
[IterativeImputer] Change: 1.914621421739149e-05, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 78/100, elapsed time 2.56
[IterativeImputer] Change: 1.5720231112181793e-05, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 79/100, elapsed time 2.58
[IterativeImputer] Change: 1.290025171107878e-05, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 80/100, elapsed time 2.61
[IterativeImputer] Change: 1.0591246197289017e-05, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 81/100, elapsed time 2.64
[IterativeImputer] Change: 8.698557056097123e-06, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 82/100, elapsed time 2.66
[IterativeImputer] Change: 7.140108702619052e-06, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 83/100, elapsed time 2.69
[IterativeImputer] Change: 5.862416212698562e-06, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 84/100, elapsed time 2.72
[IterativeImputer] Change: 4.812666251630127e-06, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 85/100, elapsed time 2.74
[IterativeImputer] Change: 3.95574311218283e-06, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 86/100, elapsed time 2.77
[IterativeImputer] Change: 3.243591818913316e-06, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 87/100, elapsed time 2.80
[IterativeImputer] Change: 2.6631019957035207e-06, scaled tolerance: 2.64e-06
[IterativeImputer] Ending imputation round 88/100, elapsed time 2.82
[IterativeImputer] Change: 2.189676731267909e-06, scaled tolerance: 2.64e-06
[IterativeImputer] Early stopping criterion reached.

In [12]:
dl1=pd.DataFrame(df2,columns=('age','bp','sg','al','su','bgr','bu','sc','sod','pot','hemo','pcv','wbcc','rbcc'))

In [13]:
dl1.head(20)

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wbcc,rbcc
0,48.0,80.000000,1.020,1.0,0.0,121.000000,36.0,1.2,138.825303,3.818908,15.4,44.0,7800.000000,5.200000
1,7.0,50.000000,1.020,4.0,0.0,152.129316,18.0,0.8,130.721286,3.892231,11.3,38.0,6000.000000,4.684685
2,50.0,74.867666,1.020,0.0,0.0,92.000000,19.0,1.2,150.000000,4.800000,14.9,48.0,4700.000000,5.400000
3,62.0,80.000000,1.010,2.0,3.0,423.000000,53.0,1.8,132.747426,4.966038,9.6,31.0,7500.000000,3.737033
4,48.0,70.000000,1.005,4.0,0.0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32.0,6700.000000,3.900000
5,30.0,80.000000,1.020,0.0,0.0,89.000000,42.0,0.5,139.000000,5.000000,16.7,52.0,10200.000000,5.000000
6,51.0,80.000000,1.010,2.0,0.0,106.000000,26.0,1.4,133.647830,3.406368,11.6,35.0,7300.000000,4.600000
7,60.0,90.000000,1.015,3.0,0.0,74.000000,25.0,1.1,142.000000,3.200000,12.2,39.0,7800.000000,4.400000
8,47.0,80.000000,1.025,0.0,0.0,124.000000,44.0,1.0,140.000000,4.900000,14.9,41.0,7000.000000,5.700000
9,75.0,60.000000,1.020,0.0,0.0,110.000000,50.0,0.7,135.000000,5.000000,14.3,40.0,8300.000000,5.800000
10,41.0,80.000000,1.020,0.0,0.0,122.000000,25.0,0.8,138.000000,5.000000,17.1,41.0,9100.000000,5.200000
11,53.0,90.000000,1.020,2.0,0.0,70.000000,107.0,7.2,114.000000,3.700000,9.5,29.0,12100.000000,3.700000
12,50.0,60.000000,1.010,2.0,4.0,490.000000,55.0,4.0,129.654816,5.303809,9.4,28.0,10101.651324,3.563175
13,52.0,80.000000,1.020,0.0,0.0,128.000000,30.0,1.2,140.000000,4.500000,15.2,52.0,4300.000000,5.700000
14,47.0,60.000000,1.020,0.0,0.0,137.000000,17.0,0.5,150.000000,3.500000,13.6,44.0,7900.000000,4.500000
15,46.0,60.000000,1.020,0.0,0.0,102.000000,27.0,0.7,142.000000,4.900000,13.2,44.0,11000.000000,5.400000
16,56.0,60.000000,1.025,0.0,0.0,132.000000,18.0,1.1,147.000000,4.700000,13.7,45.0,7500.000000,5.600000
17,68.0,70.000000,1.010,0.0,0.0,100.000000,54.0,24.0,104.000000,4.000000,12.4,36.0,5473.550467,4.174756
18,24.0,79.043223,1.015,2.0,4.0,410.000000,31.0,1.1,135.675311,5.506120,12.4,44.0,6900.000000,5.000000
19,48.0,80.000000,1.025,0.0,0.0,75.000000,22.0,0.8,137.000000,5.000000,16.8,51.0,6000.000000,6.500000

In [14]:
df3=df.drop(columns=['id','age','bp','sg','al','su','bgr','bu','sc','sod','pot','hemo','pcv','wbcc','rbcc','Label'])

In [15]:
df3

          rbc        pc         pcc          ba  htn   dm  cad appet   pe  ane
0         NaN    normal  notpresent  notpresent  yes  yes   no  good   no   no
1         NaN    normal  notpresent  notpresent   no   no   no  good   no   no
2      normal    normal  notpresent  notpresent   no   no   no  good   no   no
3      normal    normal  notpresent  notpresent   no  yes   no  poor   no  yes
4      normal  abnormal     present  notpresent  yes   no   no  poor  yes  yes
..        ...       ...         ...         ...  ...  ...  ...   ...  ...  ...
395    normal    normal  notpresent  notpresent   no   no   no  good   no   no
396       NaN  abnormal     present  notpresent  yes  yes   no  good   no  yes
397       NaN       NaN  notpresent  notpresent  yes   no  yes  poor   no   no
398  abnormal    normal     present  notpresent  yes   no  yes  good   no  yes
399    normal    normal  notpresent  notpresent   no   no   no  good   no   no

[400 rows x 10 columns]

In [16]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='constant',fill_value='Missing')
df4=imputer.fit_transform(df3)

In [17]:
dl2=pd.DataFrame(df4,columns=('rbc','pc','pcc','ba','htn','dm','cad','appet','pe','ane'))

In [18]:
dl2.head()

       rbc        pc         pcc          ba  htn   dm cad appet   pe  ane
0  Missing    normal  notpresent  notpresent  yes  yes  no  good   no   no
1  Missing    normal  notpresent  notpresent   no   no  no  good   no   no
2   normal    normal  notpresent  notpresent   no   no  no  good   no   no
3   normal    normal  notpresent  notpresent   no  yes  no  poor   no  yes
4   normal  abnormal     present  notpresent  yes   no  no  poor  yes  yes

In [19]:
from sklearn.preprocessing import OrdinalEncoder
ordi=OrdinalEncoder()

In [20]:
dl3=ordi.fit_transform(dl2)

In [21]:
dl4=pd.DataFrame(dl3,columns=('rbc','pc','pcc','ba','htn','dm','cad','appet','pe','ane'))

In [22]:
dl4

     rbc   pc  pcc   ba  htn   dm  cad  appet   pe  ane
0    0.0  2.0  1.0  1.0  2.0  2.0  1.0    1.0  2.0  1.0
1    0.0  2.0  1.0  1.0  1.0  1.0  1.0    1.0  2.0  1.0
2    2.0  2.0  1.0  1.0  1.0  1.0  1.0    1.0  2.0  1.0
3    2.0  2.0  1.0  1.0  1.0  2.0  1.0    3.0  2.0  2.0
4    2.0  1.0  2.0  1.0  2.0  1.0  1.0    3.0  3.0  2.0
..   ...  ...  ...  ...  ...  ...  ...    ...  ...  ...
395  2.0  2.0  1.0  1.0  1.0  1.0  1.0    1.0  2.0  1.0
396  0.0  1.0  2.0  1.0  2.0  2.0  1.0    1.0  2.0  2.0
397  0.0  0.0  1.0  1.0  2.0  1.0  2.0    3.0  2.0  1.0
398  1.0  2.0  2.0  1.0  2.0  1.0  2.0    1.0  2.0  2.0
399  2.0  2.0  1.0  1.0  1.0  1.0  1.0    1.0  2.0  1.0

[400 rows x 10 columns]

In [23]:
x=pd.concat([dl1,dl4],axis=1)

In [24]:
x

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,...,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane
0,48.0,80.000000,1.020000,1.000000,0.000000,121.000000,36.0,1.2,138.825303,3.818908,...,0.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0
1,7.0,50.000000,1.020000,4.000000,0.000000,152.129316,18.0,0.8,130.721286,3.892231,...,0.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0
2,50.0,74.867666,1.020000,0.000000,0.000000,92.000000,19.0,1.2,150.000000,4.800000,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0
3,62.0,80.000000,1.010000,2.000000,3.000000,423.000000,53.0,1.8,132.747426,4.966038,...,2.0,2.0,1.0,1.0,1.0,2.0,1.0,3.0,2.0,2.0
4,48.0,70.000000,1.005000,4.000000,0.000000,117.000000,56.0,3.8,111.000000,2.500000,...,2.0,1.0,2.0,1.0,2.0,1.0,1.0,3.0,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,38.0,60.000000,1.020000,0.000000,0.000000,91.000000,36.0,0.7,135.000000,3.700000,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0
396,64.0,90.000000,1.015000,3.000000,2.000000,463.000000,64.0,2.8,135.000000,4.100000,...,0.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0
397,48.0,100.000000,1.010276,2.182839,0.046629,103.000000,79.0,5.3,135.000000,6.300000,...,0.0,0.0,1.0,1.0,2.0,1.0,2.0,3.0,2.0,1.0
398,48.0,110.000000,1.015000,3.000000,0.000000,106.000000,215.0,15.2,120.000000,5.700000,...,1.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0
399,40.0,80.000000,1.020000,0.000000,0.000000,119.000000,15.0,0.7,150.000000,4.900000,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0

In [25]:
y=df['Label']

In [26]:
a=pd.concat([x,y],axis=1)

In [27]:
a

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,...,pc,pcc,ba,htn,dm,cad,appet,pe,ane,Label
0,48.0,80.000000,1.020000,1.000000,0.000000,121.000000,36.0,1.2,138.825303,3.818908,...,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,ckd
1,7.0,50.000000,1.020000,4.000000,0.000000,152.129316,18.0,0.8,130.721286,3.892231,...,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,ckd
2,50.0,74.867666,1.020000,0.000000,0.000000,92.000000,19.0,1.2,150.000000,4.800000,...,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,notckd
3,62.0,80.000000,1.010000,2.000000,3.000000,423.000000,53.0,1.8,132.747426,4.966038,...,2.0,1.0,1.0,1.0,2.0,1.0,3.0,2.0,2.0,ckd
4,48.0,70.000000,1.005000,4.000000,0.000000,117.000000,56.0,3.8,111.000000,2.500000,...,1.0,2.0,1.0,2.0,1.0,1.0,3.0,3.0,2.0,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,38.0,60.000000,1.020000,0.000000,0.000000,91.000000,36.0,0.7,135.000000,3.700000,...,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,notckd
396,64.0,90.000000,1.015000,3.000000,2.000000,463.000000,64.0,2.8,135.000000,4.100000,...,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,ckd
397,48.0,100.000000,1.010276,2.182839,0.046629,103.000000,79.0,5.3,135.000000,6.300000,...,0.0,1.0,1.0,2.0,1.0,2.0,3.0,2.0,1.0,ckd
398,48.0,110.000000,1.015000,3.000000,0.000000,106.000000,215.0,15.2,120.000000,5.700000,...,2.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,ckd
399,40.0,80.000000,1.020000,0.000000,0.000000,119.000000,15.0,0.7,150.000000,4.900000,...,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,notckd

In [28]:
#a=a.sort_values(['bu'],ascending=False)
#a.reset_index(drop=True,inplace=True)

In [29]:
#a.tail(40)

In [30]:
Label={'notckd':0,'ckd':1}
a['Label']=a['Label'].map(Label)

In [31]:
a.head(20)

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,...,pc,pcc,ba,htn,dm,cad,appet,pe,ane,Label
0,48.0,80.000000,1.020,1.0,0.0,121.000000,36.0,1.2,138.825303,3.818908,...,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,1
1,7.0,50.000000,1.020,4.0,0.0,152.129316,18.0,0.8,130.721286,3.892231,...,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1
2,50.0,74.867666,1.020,0.0,0.0,92.000000,19.0,1.2,150.000000,4.800000,...,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,0
3,62.0,80.000000,1.010,2.0,3.0,423.000000,53.0,1.8,132.747426,4.966038,...,2.0,1.0,1.0,1.0,2.0,1.0,3.0,2.0,2.0,1
4,48.0,70.000000,1.005,4.0,0.0,117.000000,56.0,3.8,111.000000,2.500000,...,1.0,2.0,1.0,2.0,1.0,1.0,3.0,3.0,2.0,1
5,30.0,80.000000,1.020,0.0,0.0,89.000000,42.0,0.5,139.000000,5.000000,...,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,0
6,51.0,80.000000,1.010,2.0,0.0,106.000000,26.0,1.4,133.647830,3.406368,...,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1
7,60.0,90.000000,1.015,3.0,0.0,74.000000,25.0,1.1,142.000000,3.200000,...,0.0,1.0,1.0,2.0,2.0,1.0,1.0,3.0,1.0,1
8,47.0,80.000000,1.025,0.0,0.0,124.000000,44.0,1.0,140.000000,4.900000,...,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,0
9,75.0,60.000000,1.020,0.0,0.0,110.000000,50.0,0.7,135.000000,5.000000,...,2.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0
10,41.0,80.000000,1.020,0.0,0.0,122.000000,25.0,0.8,138.000000,5.000000,...,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,0
11,53.0,90.000000,1.020,2.0,0.0,70.000000,107.0,7.2,114.000000,3.700000,...,1.0,2.0,1.0,2.0,2.0,1.0,3.0,2.0,2.0,1
12,50.0,60.000000,1.010,2.0,4.0,490.000000,55.0,4.0,129.654816,5.303809,...,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1
13,52.0,80.000000,1.020,0.0,0.0,128.000000,30.0,1.2,140.000000,4.500000,...,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,0
14,47.0,60.000000,1.020,0.0,0.0,137.000000,17.0,0.5,150.000000,3.500000,...,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,0
15,46.0,60.000000,1.020,0.0,0.0,102.000000,27.0,0.7,142.000000,4.900000,...,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,0
16,56.0,60.000000,1.025,0.0,0.0,132.000000,18.0,1.1,147.000000,4.700000,...,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,0
17,68.0,70.000000,1.010,0.0,0.0,100.000000,54.0,24.0,104.000000,4.000000,...,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1
18,24.0,79.043223,1.015,2.0,4.0,410.000000,31.0,1.1,135.675311,5.506120,...,1.0,1.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1
19,48.0,80.000000,1.025,0.0,0.0,75.000000,22.0,0.8,137.000000,5.000000,...,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,0

In [32]:
u=a.iloc[:,:-1]
v=a['Label']

In [33]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
k=scaler.fit_transform(u)

# Exhaustive Feature Selection

In [34]:
from mlxtend.feature_selection import ExhaustiveFeatureSelector
from sklearn.linear_model import LogisticRegression as LGR

In [35]:
feature_names=tuple(u.columns)
feature_names

('age',
 'bp',
 'sg',
 'al',
 'su',
 'bgr',
 'bu',
 'sc',
 'sod',
 'pot',
 'hemo',
 'pcv',
 'wbcc',
 'rbcc',
 'rbc',
 'pc',
 'pcc',
 'ba',
 'htn',
 'dm',
 'cad',
 'appet',
 'pe',
 'ane')

In [36]:
efs=ExhaustiveFeatureSelector(LGR(max_iter=20),min_features=1,max_features=14,scoring='accuracy',n_jobs=8,cv=3)

In [ ]:
efs.fit(k,v,custom_feature_names=feature_names)

In [ ]:
best_feature=efs.best_feature_names_

In [ ]:
best_feature

In [ ]:
df=pd.DataFrame.from_dict(efs.get_metric_dict()).T
df=df[['feature_idx','avg_score']]

In [ ]:
df.tail(50)

In [ ]:
efs.best_score_