In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import time

In [2]:
df=pd.read_csv("F:\Work\diease detection\chronic-1.csv")

In [3]:
df['sc'].unique()

array(['1.2', '0.8', '1.8', '3.8', '0.5', '1.4', '1.1', '1', '0.7', '7.2',
       '4', '24', '1.9', '2.7', '2.1', '4.6', '4.1', '0.9', '0.6', '5.2',
       '1.3', '9.6', '2.2', '1.6', '3.9', '76', '7.7', '?', '2.4', '1.5',
       '2.5', '7.3', '2', '3.4', '10.8', '6.3', '5.9', '3', '0.4', '3.25',
       '9.7', '32', '6.1', '6.4', '3.2', '3.3', '2.8', '6.7', '8.5', '15',
       '2.9', '1.7', '3.6', '5.6', '6.5', '4.4', '10.2', '11.5', '12.2',
       '5.3', '13.8', '9.2', '16.9', '6', '7.1', '18', '2.3', '13',
       '48.1', '14.2', '16.4', '7.5', '2.6', '4.3', '18.1', '11.8', '9.3',
       '6.8', '13.5', '12.8', '11.9', '12', '13.4', '13.3', '15.2'],
      dtype=object)

In [4]:
df=df.replace('?',np.nan)

In [5]:
data=df[['sg', 'al', 'bgr', 'hemo', 'pcv', 'dm', 'appet','Label']].copy()

In [6]:
#df1=df.drop(columns=['id','age','bp','sg','al','su','bgr','bu','sc','sod','pot','hemo','pcv','wbcc','rbcc'])

In [7]:
df1=data.drop(columns=['dm','appet','Label'])

In [8]:
df1

        sg   al  bgr  hemo  pcv
0     1.02    1  121  15.4   44
1     1.02    4  NaN  11.3   38
2     1.02    0   92  14.9   48
3     1.01    2  423   9.6   31
4    1.005    4  117  11.2   32
..     ...  ...  ...   ...  ...
395   1.02    0   91    14   46
396  1.015    3  463  12.2   40
397    NaN  NaN  103   6.3   19
398  1.015    3  106   8.6   26
399   1.02    0  119   NaN  NaN

[400 rows x 5 columns]

In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [10]:
lr=LinearRegression()
imp=IterativeImputer(estimator=lr,verbose=2,max_iter=100, tol=1e-10, imputation_order='roman')

In [11]:
df2=imp.fit_transform(df1)

[IterativeImputer] Completing matrix with shape (400, 5)
[IterativeImputer] Ending imputation round 1/100, elapsed time 0.02
[IterativeImputer] Change: 76.68798689603847, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 2/100, elapsed time 0.03
[IterativeImputer] Change: 21.08112223418534, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 3/100, elapsed time 0.04
[IterativeImputer] Change: 4.827888059510066, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 4/100, elapsed time 0.05
[IterativeImputer] Change: 2.27461307639539, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 5/100, elapsed time 0.06
[IterativeImputer] Change: 1.4042869617008265, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 6/100, elapsed time 0.06
[IterativeImputer] Change: 0.8932791462653522, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 7/100, elapsed time 0.07
[IterativeImputer] Change: 0.7417811696083974, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 8/100, elapsed time 0.08
[IterativeImputer] Change: 0.6171859558815067, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 9/100, elapsed time 0.09
[IterativeImputer] Change: 0.5142552896969752, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 10/100, elapsed time 0.10
[IterativeImputer] Change: 0.42894689841472244, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 11/100, elapsed time 0.10
[IterativeImputer] Change: 0.3580745890571504, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 12/100, elapsed time 0.11
[IterativeImputer] Change: 0.2990900508353105, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 13/100, elapsed time 0.12
[IterativeImputer] Change: 0.2499332381114292, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 14/100, elapsed time 0.13
[IterativeImputer] Change: 0.20892524154280845, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 15/100, elapsed time 0.14
[IterativeImputer] Change: 0.17468919666604932, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 16/100, elapsed time 0.15
[IterativeImputer] Change: 0.146090488628275, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 17/100, elapsed time 0.16
[IterativeImputer] Change: 0.1221906563278774, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 18/100, elapsed time 0.17
[IterativeImputer] Change: 0.10221127341909164, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 19/100, elapsed time 0.18
[IterativeImputer] Change: 0.08550525874103765, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 20/100, elapsed time 0.20
[IterativeImputer] Change: 0.07153383037076666, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 21/100, elapsed time 0.21
[IterativeImputer] Change: 0.0598478232788866, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 22/100, elapsed time 0.22
[IterativeImputer] Change: 0.05007243334781131, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 23/100, elapsed time 0.23
[IterativeImputer] Change: 0.04189468741704738, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 24/100, elapsed time 0.25
[IterativeImputer] Change: 0.03505310599033229, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 25/100, elapsed time 0.25
[IterativeImputer] Change: 0.029329145360111664, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 26/100, elapsed time 0.26
[IterativeImputer] Change: 0.024540094078545627, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 27/100, elapsed time 0.27
[IterativeImputer] Change: 0.020533164752961186, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 28/100, elapsed time 0.28
[IterativeImputer] Change: 0.017180572553701756, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 29/100, elapsed time 0.30
[IterativeImputer] Change: 0.014375430954468138, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 30/100, elapsed time 0.30
[IterativeImputer] Change: 0.01202832606082338, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 31/100, elapsed time 0.31
[IterativeImputer] Change: 0.010064455497418079, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 32/100, elapsed time 0.32
[IterativeImputer] Change: 0.00842123766727676, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 33/100, elapsed time 0.34
[IterativeImputer] Change: 0.0070463133429523594, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 34/100, elapsed time 0.35
[IterativeImputer] Change: 0.005895874763415909, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 35/100, elapsed time 0.36
[IterativeImputer] Change: 0.004933268288490611, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 36/100, elapsed time 0.37
[IterativeImputer] Change: 0.004127825658140516, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 37/100, elapsed time 0.38
[IterativeImputer] Change: 0.0034538863491895277, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 38/100, elapsed time 0.40
[IterativeImputer] Change: 0.00288997972018068, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 39/100, elapsed time 0.41
[IterativeImputer] Change: 0.0024181407890511153, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 40/100, elapsed time 0.42
[IterativeImputer] Change: 0.00202333778549435, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 41/100, elapsed time 0.43
[IterativeImputer] Change: 0.001692993200706594, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 42/100, elapsed time 0.44
[IterativeImputer] Change: 0.0014165830556267522, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 43/100, elapsed time 0.45
[IterativeImputer] Change: 0.001185301611608125, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 44/100, elapsed time 0.45
[IterativeImputer] Change: 0.0009917808278154805, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 45/100, elapsed time 0.46
[IterativeImputer] Change: 0.0008298556272208213, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 46/100, elapsed time 0.47
[IterativeImputer] Change: 0.0006943674886508155, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 47/100, elapsed time 0.48
[IterativeImputer] Change: 0.0005810001095634121, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 48/100, elapsed time 0.49
[IterativeImputer] Change: 0.0004861418976431775, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 49/100, elapsed time 0.50
[IterativeImputer] Change: 0.0004067709141073461, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 50/100, elapsed time 0.50
[IterativeImputer] Change: 0.0003403586045052087, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 51/100, elapsed time 0.51
[IterativeImputer] Change: 0.0002847892429664878, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 52/100, elapsed time 0.52
[IterativeImputer] Change: 0.00023829253189844302, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 53/100, elapsed time 0.53
[IterativeImputer] Change: 0.00019938720603596138, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 54/100, elapsed time 0.54
[IterativeImputer] Change: 0.0001668338414508863, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 55/100, elapsed time 0.59
[IterativeImputer] Change: 0.00013959537119245802, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 56/100, elapsed time 0.63
[IterativeImputer] Change: 0.00011680404782765663, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 57/100, elapsed time 0.66
[IterativeImputer] Change: 9.773379792132886e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 58/100, elapsed time 0.67
[IterativeImputer] Change: 8.177709264867161e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 59/100, elapsed time 0.69
[IterativeImputer] Change: 6.842559216191368e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 60/100, elapsed time 0.71
[IterativeImputer] Change: 5.725395217037743e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 61/100, elapsed time 0.72
[IterativeImputer] Change: 4.790627317441398e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 62/100, elapsed time 0.72
[IterativeImputer] Change: 4.008476200789701e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 63/100, elapsed time 0.73
[IterativeImputer] Change: 3.35402459361589e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 64/100, elapsed time 0.74
[IterativeImputer] Change: 2.8064233359437196e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 65/100, elapsed time 0.75
[IterativeImputer] Change: 2.3482273190600367e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 66/100, elapsed time 0.75
[IterativeImputer] Change: 1.9648395771065807e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 67/100, elapsed time 0.76
[IterativeImputer] Change: 1.6440463780575953e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 68/100, elapsed time 0.77

[IterativeImputer] Change: 1.3756281078247667e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 69/100, elapsed time 0.78
[IterativeImputer] Change: 1.1510336754394501e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 70/100, elapsed time 0.79
[IterativeImputer] Change: 9.63108086282638e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 71/100, elapsed time 0.80
[IterativeImputer] Change: 8.058645200037517e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 72/100, elapsed time 0.81
[IterativeImputer] Change: 6.742936297099433e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 73/100, elapsed time 0.82
[IterativeImputer] Change: 5.642039103248564e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 74/100, elapsed time 0.82
[IterativeImputer] Change: 4.7208818081401205e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 75/100, elapsed time 0.83
[IterativeImputer] Change: 3.950118863338403e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 76/100, elapsed time 0.84
[IterativeImputer] Change: 3.305195964031782e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 77/100, elapsed time 0.85
[IterativeImputer] Change: 2.7655677414806235e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 78/100, elapsed time 0.85
[IterativeImputer] Change: 2.314042771844882e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 79/100, elapsed time 0.86
[IterativeImputer] Change: 1.9362367240649547e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 80/100, elapsed time 0.87
[IterativeImputer] Change: 1.6201138708371587e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 81/100, elapsed time 0.88
[IterativeImputer] Change: 1.3556035145523282e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 82/100, elapsed time 0.89
[IterativeImputer] Change: 1.1342784702605968e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 83/100, elapsed time 0.89
[IterativeImputer] Change: 9.490888446261891e-07, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 84/100, elapsed time 0.90
[IterativeImputer] Change: 7.94134420223358e-07, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 85/100, elapsed time 0.91
[IterativeImputer] Change: 6.644789669607576e-07, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 86/100, elapsed time 0.92
[IterativeImputer] Change: 5.559916638198104e-07, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 87/100, elapsed time 0.92
[IterativeImputer] Change: 4.652169047769661e-07, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 88/100, elapsed time 0.93
[IterativeImputer] Change: 3.8926258016935833e-07, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 89/100, elapsed time 0.94
[IterativeImputer] Change: 3.2570892805061646e-07, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 90/100, elapsed time 0.95
[IterativeImputer] Change: 2.725317671536942e-07, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 91/100, elapsed time 0.96
[IterativeImputer] Change: 2.2803648969116352e-07, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 92/100, elapsed time 0.97
[IterativeImputer] Change: 1.9080572277729857e-07, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 93/100, elapsed time 0.98
[IterativeImputer] Change: 1.5965357014202652e-07, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 94/100, elapsed time 0.99
[IterativeImputer] Change: 1.335876498309574e-07, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 95/100, elapsed time 1.00
[IterativeImputer] Change: 1.1177715997234827e-07, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 96/100, elapsed time 1.01
[IterativeImputer] Change: 9.352777885496266e-08, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 97/100, elapsed time 1.02
[IterativeImputer] Change: 7.825767034397302e-08, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 98/100, elapsed time 1.03
[IterativeImputer] Change: 6.548098197001195e-08, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 99/100, elapsed time 1.04
[IterativeImputer] Change: 5.479013354126039e-08, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 100/100, elapsed time 1.05
[IterativeImputer] Change: 4.584477197866477e-08, scaled tolerance: 4.9e-08
[IterativeImputer] Early stopping criterion reached.

In [12]:
dl1=pd.DataFrame(df2,columns=('sg','al','bgr','hemo','pcv'))

In [13]:
dl1.head(20)

       sg   al         bgr  hemo   pcv
0   1.020  1.0  121.000000  15.4  44.0
1   1.020  4.0  189.158199  11.3  38.0
2   1.020  0.0   92.000000  14.9  48.0
3   1.010  2.0  423.000000   9.6  31.0
4   1.005  4.0  117.000000  11.2  32.0
5   1.020  0.0   89.000000  16.7  52.0
6   1.010  2.0  106.000000  11.6  35.0
7   1.015  3.0   74.000000  12.2  39.0
8   1.025  0.0  124.000000  14.9  41.0
9   1.020  0.0  110.000000  14.3  40.0
10  1.020  0.0  122.000000  17.1  41.0
11  1.020  2.0   70.000000   9.5  29.0
12  1.010  2.0  490.000000   9.4  28.0
13  1.020  0.0  128.000000  15.2  52.0
14  1.020  0.0  137.000000  13.6  44.0
15  1.020  0.0  102.000000  13.2  44.0
16  1.025  0.0  132.000000  13.7  45.0
17  1.010  0.0  100.000000  12.4  36.0
18  1.015  2.0  410.000000  12.4  44.0
19  1.025  0.0   75.000000  16.8  51.0

In [14]:
df3=data.drop(columns=['sg','al','bgr','hemo','pcv','Label'])

In [15]:
df3

      dm appet
0    yes  good
1     no  good
2     no  good
3    yes  poor
4     no  poor
..   ...   ...
395   no  good
396  yes  good
397   no  poor
398   no  good
399   no  good

[400 rows x 2 columns]

In [16]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='constant',fill_value='Missing')
df4=imputer.fit_transform(df3)

In [17]:
dl2=pd.DataFrame(df4,columns=('dm','appet'))

In [18]:
dl2.head()

    dm appet
0  yes  good
1   no  good
2   no  good
3  yes  poor
4   no  poor

In [19]:
from sklearn.preprocessing import OrdinalEncoder
ordi=OrdinalEncoder()

In [20]:
dl3=ordi.fit_transform(dl2)

In [21]:
dl4=pd.DataFrame(dl3,columns=('dm','appet'))

In [22]:
dl4

      dm  appet
0    2.0    1.0
1    1.0    1.0
2    1.0    1.0
3    2.0    3.0
4    1.0    3.0
..   ...    ...
395  1.0    1.0
396  2.0    1.0
397  1.0    3.0
398  1.0    1.0
399  1.0    1.0

[400 rows x 2 columns]

In [23]:
x=pd.concat([dl1,dl4],axis=1)

In [24]:
x

          sg        al         bgr       hemo        pcv   dm  appet
0    1.02000  1.000000  121.000000  15.400000  44.000000  2.0    1.0
1    1.02000  4.000000  189.158199  11.300000  38.000000  1.0    1.0
2    1.02000  0.000000   92.000000  14.900000  48.000000  1.0    1.0
3    1.01000  2.000000  423.000000   9.600000  31.000000  2.0    3.0
4    1.00500  4.000000  117.000000  11.200000  32.000000  1.0    3.0
..       ...       ...         ...        ...        ...  ...    ...
395  1.02000  0.000000   91.000000  14.000000  46.000000  1.0    1.0
396  1.01500  3.000000  463.000000  12.200000  40.000000  2.0    1.0
397  1.01059  2.745462  103.000000   6.300000  19.000000  1.0    3.0
398  1.01500  3.000000  106.000000   8.600000  26.000000  1.0    1.0
399  1.02000  0.000000  119.000000  14.122026  43.147852  1.0    1.0

[400 rows x 7 columns]

In [25]:
y=df['Label']

In [26]:
a=pd.concat([x,y],axis=1)

In [27]:
a

          sg        al         bgr       hemo        pcv   dm  appet   Label
0    1.02000  1.000000  121.000000  15.400000  44.000000  2.0    1.0     ckd
1    1.02000  4.000000  189.158199  11.300000  38.000000  1.0    1.0     ckd
2    1.02000  0.000000   92.000000  14.900000  48.000000  1.0    1.0  notckd
3    1.01000  2.000000  423.000000   9.600000  31.000000  2.0    3.0     ckd
4    1.00500  4.000000  117.000000  11.200000  32.000000  1.0    3.0     ckd
..       ...       ...         ...        ...        ...  ...    ...     ...
395  1.02000  0.000000   91.000000  14.000000  46.000000  1.0    1.0  notckd
396  1.01500  3.000000  463.000000  12.200000  40.000000  2.0    1.0     ckd
397  1.01059  2.745462  103.000000   6.300000  19.000000  1.0    3.0     ckd
398  1.01500  3.000000  106.000000   8.600000  26.000000  1.0    1.0     ckd
399  1.02000  0.000000  119.000000  14.122026  43.147852  1.0    1.0  notckd

[400 rows x 8 columns]

In [28]:
#a=a.sort_values(['bu'],ascending=False)
#a.reset_index(drop=True,inplace=True)

In [29]:
#a.tail(40)

In [30]:
Label={'notckd':0,'ckd':1}
a['Label']=a['Label'].map(Label)

In [31]:
a.head(20)

       sg   al         bgr  hemo   pcv   dm  appet  Label
0   1.020  1.0  121.000000  15.4  44.0  2.0    1.0      1
1   1.020  4.0  189.158199  11.3  38.0  1.0    1.0      1
2   1.020  0.0   92.000000  14.9  48.0  1.0    1.0      0
3   1.010  2.0  423.000000   9.6  31.0  2.0    3.0      1
4   1.005  4.0  117.000000  11.2  32.0  1.0    3.0      1
5   1.020  0.0   89.000000  16.7  52.0  1.0    1.0      0
6   1.010  2.0  106.000000  11.6  35.0  1.0    1.0      1
7   1.015  3.0   74.000000  12.2  39.0  2.0    1.0      1
8   1.025  0.0  124.000000  14.9  41.0  1.0    1.0      0
9   1.020  0.0  110.000000  14.3  40.0  1.0    0.0      0
10  1.020  0.0  122.000000  17.1  41.0  1.0    1.0      0
11  1.020  2.0   70.000000   9.5  29.0  2.0    3.0      1
12  1.010  2.0  490.000000   9.4  28.0  2.0    1.0      1
13  1.020  0.0  128.000000  15.2  52.0  1.0    1.0      0
14  1.020  0.0  137.000000  13.6  44.0  1.0    1.0      0
15  1.020  0.0  102.000000  13.2  44.0  1.0    1.0      0
16  1.025  0.0  132.000000  13.7  45.0  1.0    1.0      0
17  1.010  0.0  100.000000  12.4  36.0  1.0    1.0      1
18  1.015  2.0  410.000000  12.4  44.0  2.0    1.0      1
19  1.025  0.0   75.000000  16.8  51.0  1.0    1.0      0

In [32]:
u=a.iloc[:,:-1]
v=a['Label']

In [33]:
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import SVMSMOTE

In [34]:
smote=SMOTE()
sm = SVMSMOTE()

In [35]:
x_train_resample,y_train_resample=sm.fit_resample(u,v)

In [36]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
k=scaler.fit_transform(x_train_resample)

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(k,y_train_resample,test_size=0.2, random_state=0)

In [38]:
from sklearn.model_selection import KFold
from sklearn.model_selection import ShuffleSplit
fold=ShuffleSplit(n_splits=5, test_size=0.1, random_state=0)
fold1=KFold(5)
from sklearn.model_selection import cross_val_score

In [39]:
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [40]:
svm=SVC(C=1)
knn=KNeighborsClassifier(n_neighbors=1,weights= 'distance',metric='manhattan')
gdb=GradientBoostingClassifier(n_estimators=400,max_depth=6,learning_rate=0.1,min_samples_leaf=4)
lgb=LGBMClassifier(n_estimators=100,max_depth=2,learning_rate=0.05,min_child_weight=3)
xgb=XGBClassifier(n_estimators=400,max_depth=10,learning_rate=0.15,min_child_weight=8,eval_metric='error')

In [41]:
labels=['svm','knn','gdb','xgb','lgb']

In [42]:
for clf,label in zip([svm,knn,gdb,xgb,lgb],labels):
    training_start = time.perf_counter()
    results_svm=cross_val_score(clf,x_train,y_train,cv=fold,scoring='accuracy')
    training_end = time.perf_counter()
    train_time = training_end-training_start
    print("Time consumed for training: %4.3f seconds" % (train_time))
    print("%0.4faccuracy with a standard deviation of %0.4f" % (results_svm.mean(), results_svm.std()),label)

Time consumed for training: 0.035 seconds
1.0000accuracy with a standard deviation of 0.0000 svm
Time consumed for training: 0.025 seconds
1.0000accuracy with a standard deviation of 0.0000 knn
Time consumed for training: 5.271 seconds
0.9850accuracy with a standard deviation of 0.0200 gdb

C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

Time consumed for training: 1.397 seconds
0.9850accuracy with a standard deviation of 0.0122 xgb
Time consumed for training: 0.224 seconds
1.0000accuracy with a standard deviation of 0.0000 lgb

In [43]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score

In [44]:
for clf,label in zip([svm,knn,gdb,xgb,lgb],labels):
    training_start = time.perf_counter()
    clf.fit(x_train,y_train)
    training_end = time.perf_counter()
    train_time = training_end-training_start
    print("Time consumed for training: %4.3f seconds" % (train_time))
    y_pred=clf.predict(x_test)
    print(accuracy_score(y_test,y_pred),label)
    print(confusion_matrix(y_test,y_pred))
    print(precision_score(y_test,y_pred))
    print(recall_score(y_test,y_pred))
    print(f1_score(y_test,y_pred))
    print(roc_auc_score(y_test,y_pred))

Time consumed for training: 0.006 seconds
1.0 svm
[[45  0]
 [ 0 55]]
1.0
1.0
1.0
1.0
Time consumed for training: 0.003 seconds
1.0 knn
[[45  0]
 [ 0 55]]
1.0
1.0
1.0
1.0
Time consumed for training: 1.117 seconds
0.98 gdb
[[45  0]
 [ 2 53]]
1.0
0.9636363636363636
0.9814814814814815
0.9818181818181818

C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

Time consumed for training: 0.245 seconds
0.99 xgb
[[45  0]
 [ 1 54]]
1.0
0.9818181818181818
0.9908256880733944
0.990909090909091
Time consumed for training: 0.029 seconds
0.99 lgb
[[45  0]
 [ 1 54]]
1.0
0.9818181818181818
0.9908256880733944
0.990909090909091

In [45]:
from mlxtend.evaluate import combined_ftest_5x2cv

In [64]:
f, p = combined_ftest_5x2cv(estimator1=xgb,
                            estimator2=lgb,
                            X=k, y=y_train_resample,
                            random_seed=1)

C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

In [65]:
print('F statistic: %.3f' % f)
print('p value: %.3f' % p)

F statistic: 5.194
p value: 0.041