In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import time

In [2]:
df=pd.read_csv("F:\Work\diease detection\ckd\diease detection\chronic-1.csv")

In [3]:
df=df.replace('?',np.nan)

In [4]:
data=df[['sg', 'al', 'su', 'bgr', 'sc', 'hemo', 'pcv', 'rbcc', 'rbc', 'htn',
       'dm', 'appet','Label']].copy()

In [5]:
#df1=df.drop(columns=['id','age','bp','sg','al','su','bgr','bu','sc','sod','pot','hemo','pcv','wbcc','rbcc'])

In [6]:
data

,sg,al,su,bgr,sc,hemo,pcv,rbcc,rbc,htn,dm,appet,Label
0,1.02,1,0,121,1.2,15.4,44,5.2,NaN,yes,yes,good,ckd
1,1.02,4,0,NaN,0.8,11.3,38,NaN,NaN,no,no,good,ckd
2,1.02,0,0,92,1.2,14.9,48,5.4,normal,no,no,good,notckd
3,1.01,2,3,423,1.8,9.6,31,NaN,normal,no,yes,poor,ckd
4,1.005,4,0,117,3.8,11.2,32,3.9,normal,yes,no,poor,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,1.02,0,0,91,0.7,14,46,5.8,normal,no,no,good,notckd
396,1.015,3,2,463,2.8,12.2,40,4.6,NaN,yes,yes,good,ckd
397,NaN,NaN,NaN,103,5.3,6.3,19,2.6,NaN,yes,no,poor,ckd
398,1.015,3,0,106,15.2,8.6,26,2.5,abnormal,yes,no,good,ckd
399,1.02,0,0,119,0.7,NaN,NaN,NaN,normal,no,no,good,notckd

In [7]:
df1=data.drop(columns=['rbc','htn','dm','appet','Label'])

In [8]:
df1

        sg   al   su  bgr    sc  hemo  pcv rbcc
0     1.02    1    0  121   1.2  15.4   44  5.2
1     1.02    4    0  NaN   0.8  11.3   38  NaN
2     1.02    0    0   92   1.2  14.9   48  5.4
3     1.01    2    3  423   1.8   9.6   31  NaN
4    1.005    4    0  117   3.8  11.2   32  3.9
..     ...  ...  ...  ...   ...   ...  ...  ...
395   1.02    0    0   91   0.7    14   46  5.8
396  1.015    3    2  463   2.8  12.2   40  4.6
397    NaN  NaN  NaN  103   5.3   6.3   19  2.6
398  1.015    3    0  106  15.2   8.6   26  2.5
399   1.02    0    0  119   0.7   NaN  NaN  NaN

[400 rows x 8 columns]

In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [10]:
lr=LinearRegression()
imp=IterativeImputer(estimator=lr,verbose=2,max_iter=100, tol=1e-10, imputation_order='roman')

In [11]:
df2=imp.fit_transform(df1)

[IterativeImputer] Completing matrix with shape (400, 8)
[IterativeImputer] Ending imputation round 1/100, elapsed time 0.01
[IterativeImputer] Change: 182.27250463282877, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 2/100, elapsed time 0.01
[IterativeImputer] Change: 18.887880713988565, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 3/100, elapsed time 0.03
[IterativeImputer] Change: 15.664749386650762, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 4/100, elapsed time 0.04
[IterativeImputer] Change: 12.960883525117847, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 5/100, elapsed time 0.04
[IterativeImputer] Change: 10.635872032214749, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 6/100, elapsed time 0.05
[IterativeImputer] Change: 8.778279890974257, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 7/100, elapsed time 0.05
[IterativeImputer] Change: 7.293859443214355, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 8/100, elapsed time 0.06
[IterativeImputer] Change: 6.097257168910758, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 9/100, elapsed time 0.06
[IterativeImputer] Change: 5.122350285048212, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 10/100, elapsed time 0.06
[IterativeImputer] Change: 4.320137985342465, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 11/100, elapsed time 0.08
[IterativeImputer] Change: 3.6544616572392647, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 12/100, elapsed time 0.08
[IterativeImputer] Change: 3.0983620393453846, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 13/100, elapsed time 0.08
[IterativeImputer] Change: 2.6313870731610365, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 14/100, elapsed time 0.09
[IterativeImputer] Change: 2.237712066310138, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 15/100, elapsed time 0.09
[IterativeImputer] Change: 1.904854828565497, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 16/100, elapsed time 0.11
[IterativeImputer] Change: 1.6228000632399924, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 17/100, elapsed time 0.11
[IterativeImputer] Change: 1.3833970089423182, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 18/100, elapsed time 0.11
[IterativeImputer] Change: 1.1799374191629, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 19/100, elapsed time 0.12
[IterativeImputer] Change: 1.0068526656447925, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 20/100, elapsed time 0.12
[IterativeImputer] Change: 0.8594903900574984, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 21/100, elapsed time 0.12
[IterativeImputer] Change: 0.7339453023045939, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 22/100, elapsed time 0.14
[IterativeImputer] Change: 0.626927785105708, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 23/100, elapsed time 0.14
[IterativeImputer] Change: 0.5356596790228147, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 24/100, elapsed time 0.14
[IterativeImputer] Change: 0.457790206952406, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 25/100, elapsed time 0.15
[IterativeImputer] Change: 0.39132725124490286, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 26/100, elapsed time 0.15
[IterativeImputer] Change: 0.3345806279568748, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 27/100, elapsed time 0.17
[IterativeImputer] Change: 0.28611492805261185, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 28/100, elapsed time 0.17
[IterativeImputer] Change: 0.24471010866445653, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 29/100, elapsed time 0.17
[IterativeImputer] Change: 0.2093284367993331, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 30/100, elapsed time 0.19
[IterativeImputer] Change: 0.17908668472937483, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 31/100, elapsed time 0.19
[IterativeImputer] Change: 0.1532326937988091, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 32/100, elapsed time 0.19
[IterativeImputer] Change: 0.13112558801107377, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 33/100, elapsed time 0.21
[IterativeImputer] Change: 0.1122190466934383, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 34/100, elapsed time 0.21
[IterativeImputer] Change: 0.09604714737609088, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 35/100, elapsed time 0.21
[IterativeImputer] Change: 0.08221237199491815, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 36/100, elapsed time 0.23
[IterativeImputer] Change: 0.07037543677889158, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 37/100, elapsed time 0.24
[IterativeImputer] Change: 0.06024666140576196, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 38/100, elapsed time 0.24
[IterativeImputer] Change: 0.05157863884290026, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 39/100, elapsed time 0.25
[IterativeImputer] Change: 0.04416000538541032, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 40/100, elapsed time 0.25
[IterativeImputer] Change: 0.037810142219472764, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 41/100, elapsed time 0.26
[IterativeImputer] Change: 0.032374666364544114, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 42/100, elapsed time 0.26
[IterativeImputer] Change: 0.02772159118456541, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 43/100, elapsed time 0.28
[IterativeImputer] Change: 0.023738055218216036, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 44/100, elapsed time 0.28
[IterativeImputer] Change: 0.020327533796358432, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 45/100, elapsed time 0.30
[IterativeImputer] Change: 0.01740746112955449, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 46/100, elapsed time 0.30
[IterativeImputer] Change: 0.014907201496520583, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 47/100, elapsed time 0.31
[IterativeImputer] Change: 0.012766317690830364, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 48/100, elapsed time 0.31
[IterativeImputer] Change: 0.010933092544828105, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 49/100, elapsed time 0.31
[IterativeImputer] Change: 0.009363266218734179, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 50/100, elapsed time 0.33
[IterativeImputer] Change: 0.008018957393461923, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 51/100, elapsed time 0.33
[IterativeImputer] Change: 0.006867741340247369, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 52/100, elapsed time 0.35
[IterativeImputer] Change: 0.0058818619021845375, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 53/100, elapsed time 0.35
[IterativeImputer] Change: 0.005037557718557739, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 54/100, elapsed time 0.35
[IterativeImputer] Change: 0.00431448610215357, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 55/100, elapsed time 0.36
[IterativeImputer] Change: 0.0036952302630559597, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 56/100, elapsed time 0.36
[IterativeImputer] Change: 0.003164877777740438, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 57/100, elapsed time 0.38
[IterativeImputer] Change: 0.0027106599708472956, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 58/100, elapsed time 0.38
[IterativeImputer] Change: 0.0023216433246757706, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 59/100, elapsed time 0.40
[IterativeImputer] Change: 0.0019884654238453425, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 60/100, elapsed time 0.40
[IterativeImputer] Change: 0.0017031089687642442, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 61/100, elapsed time 0.41
[IterativeImputer] Change: 0.001458708324972413, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 62/100, elapsed time 0.41
[IterativeImputer] Change: 0.0012493839828191522, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 63/100, elapsed time 0.41
[IterativeImputer] Change: 0.0010701007909317273, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 64/100, elapsed time 0.43
[IterativeImputer] Change: 0.0009165466347105244, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 65/100, elapsed time 0.43
[IterativeImputer] Change: 0.0007850285403188106, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 66/100, elapsed time 0.44
[IterativeImputer] Change: 0.0006723837498752161, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 67/100, elapsed time 0.45
[IterativeImputer] Change: 0.00057590354672854, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 68/100, elapsed time 0.45
[IterativeImputer] Change: 0.0004932680458558103, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 69/100, elapsed time 0.46
[IterativeImputer] Change: 0.00042249037619845886, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 70/100, elapsed time 0.46
[IterativeImputer] Change: 0.000361868842745805, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 71/100, elapsed time 0.48
[IterativeImputer] Change: 0.00030994600147193907, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 72/100, elapsed time 0.48
[IterativeImputer] Change: 0.00026547357156836426, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 73/100, elapsed time 0.48
[IterativeImputer] Change: 0.00022738243967013183, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 74/100, elapsed time 0.50
[IterativeImputer] Change: 0.0001947569056730547, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 75/100, elapsed time 0.50
[IterativeImputer] Change: 0.0001668126923612956, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 76/100, elapsed time 0.51
[IterativeImputer] Change: 0.000142878069742558, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 77/100, elapsed time 0.51
[IterativeImputer] Change: 0.00012237769452205782, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 78/100, elapsed time 0.51
[IterativeImputer] Change: 0.00010481879442791886, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 79/100, elapsed time 0.53
[IterativeImputer] Change: 8.977929731246448e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 80/100, elapsed time 0.53
[IterativeImputer] Change: 7.689771067243001e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 81/100, elapsed time 0.55
[IterativeImputer] Change: 6.586439794764587e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 82/100, elapsed time 0.55
[IterativeImputer] Change: 5.641416382307085e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 83/100, elapsed time 0.56

[IterativeImputer] Change: 4.831986070175098e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 84/100, elapsed time 0.56
[IterativeImputer] Change: 4.1386937188025996e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 85/100, elapsed time 0.58
[IterativeImputer] Change: 3.5448756235068046e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 86/100, elapsed time 0.58
[IterativeImputer] Change: 3.0362583418375166e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 87/100, elapsed time 0.59
[IterativeImputer] Change: 2.6006177284321197e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 88/100, elapsed time 0.60
[IterativeImputer] Change: 2.2274826601886843e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 89/100, elapsed time 0.60
[IterativeImputer] Change: 1.907885294238909e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 90/100, elapsed time 0.61
[IterativeImputer] Change: 1.6341434113886777e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 91/100, elapsed time 0.61
[IterativeImputer] Change: 1.3996778926772535e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 92/100, elapsed time 0.63
[IterativeImputer] Change: 1.1988534446283339e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 93/100, elapsed time 0.63
[IterativeImputer] Change: 1.0268428294546439e-05, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 94/100, elapsed time 0.65
[IterativeImputer] Change: 8.795124742722038e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 95/100, elapsed time 0.65
[IterativeImputer] Change: 7.533209007704045e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 96/100, elapsed time 0.65
[IterativeImputer] Change: 6.452350806540608e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 97/100, elapsed time 0.66
[IterativeImputer] Change: 5.526576610570544e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 98/100, elapsed time 0.66
[IterativeImputer] Change: 4.7336265731612315e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 99/100, elapsed time 0.68
[IterativeImputer] Change: 4.054451490320687e-06, scaled tolerance: 4.9e-08
[IterativeImputer] Ending imputation round 100/100, elapsed time 0.68
[IterativeImputer] Change: 3.4727229434317053e-06, scaled tolerance: 4.9e-08

C:\Users\MD SABBIR SK\anaconda3\lib\site-packages\sklearn\impute\_iterative.py:685: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn("[IterativeImputer] Early stopping criterion not"

In [12]:
dl1=pd.DataFrame(df2,columns=('sg','al','su','bgr','sc','hemo','pcv','rbcc'))

In [13]:
dl1.head(20)

       sg   al   su         bgr    sc  hemo   pcv      rbcc
0   1.020  1.0  0.0  121.000000   1.2  15.4  44.0  5.200000
1   1.020  4.0  0.0  155.893755   0.8  11.3  38.0  4.483714
2   1.020  0.0  0.0   92.000000   1.2  14.9  48.0  5.400000
3   1.010  2.0  3.0  423.000000   1.8   9.6  31.0  3.742738
4   1.005  4.0  0.0  117.000000   3.8  11.2  32.0  3.900000
5   1.020  0.0  0.0   89.000000   0.5  16.7  52.0  5.000000
6   1.010  2.0  0.0  106.000000   1.4  11.6  35.0  4.600000
7   1.015  3.0  0.0   74.000000   1.1  12.2  39.0  4.400000
8   1.025  0.0  0.0  124.000000   1.0  14.9  41.0  5.700000
9   1.020  0.0  0.0  110.000000   0.7  14.3  40.0  5.800000
10  1.020  0.0  0.0  122.000000   0.8  17.1  41.0  5.200000
11  1.020  2.0  0.0   70.000000   7.2   9.5  29.0  3.700000
12  1.010  2.0  4.0  490.000000   4.0   9.4  28.0  3.561102
13  1.020  0.0  0.0  128.000000   1.2  15.2  52.0  5.700000
14  1.020  0.0  0.0  137.000000   0.5  13.6  44.0  4.500000
15  1.020  0.0  0.0  102.000000   0.7  13.2  44.0  5.400000
16  1.025  0.0  0.0  132.000000   1.1  13.7  45.0  5.600000
17  1.010  0.0  0.0  100.000000  24.0  12.4  36.0  4.152490
18  1.015  2.0  4.0  410.000000   1.1  12.4  44.0  5.000000
19  1.025  0.0  0.0   75.000000   0.8  16.8  51.0  6.500000

In [14]:
df3=data.drop(columns=['sg','al','su','bgr','sc','hemo','pcv','rbcc','Label'])

In [15]:
df3

          rbc  htn   dm appet
0         NaN  yes  yes  good
1         NaN   no   no  good
2      normal   no   no  good
3      normal   no  yes  poor
4      normal  yes   no  poor
..        ...  ...  ...   ...
395    normal   no   no  good
396       NaN  yes  yes  good
397       NaN  yes   no  poor
398  abnormal  yes   no  good
399    normal   no   no  good

[400 rows x 4 columns]

In [16]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='constant',fill_value='Missing')
df4=imputer.fit_transform(df3)

In [17]:
dl2=pd.DataFrame(df4,columns=('rbc','htn','dm','appet'))

In [18]:
dl2.head()

       rbc  htn   dm appet
0  Missing  yes  yes  good
1  Missing   no   no  good
2   normal   no   no  good
3   normal   no  yes  poor
4   normal  yes   no  poor

In [19]:
from sklearn.preprocessing import OrdinalEncoder
ordi=OrdinalEncoder()

In [20]:
dl3=ordi.fit_transform(dl2)

In [21]:
dl4=pd.DataFrame(dl3,columns=('rbc','htn','dm','appet'))

In [22]:
dl4

     rbc  htn   dm  appet
0    0.0  2.0  2.0    1.0
1    0.0  1.0  1.0    1.0
2    2.0  1.0  1.0    1.0
3    2.0  1.0  2.0    3.0
4    2.0  2.0  1.0    3.0
..   ...  ...  ...    ...
395  2.0  1.0  1.0    1.0
396  0.0  2.0  2.0    1.0
397  0.0  2.0  1.0    3.0
398  1.0  2.0  1.0    1.0
399  2.0  1.0  1.0    1.0

[400 rows x 4 columns]

In [23]:
x=pd.concat([dl1,dl4],axis=1)

In [24]:
x

,sg,al,su,bgr,sc,hemo,pcv,rbcc,rbc,htn,dm,appet
0,1.020000,1.000000,0.000000,121.000000,1.2,15.40000,44.000000,5.200000,0.0,2.0,2.0,1.0
1,1.020000,4.000000,0.000000,155.893755,0.8,11.30000,38.000000,4.483714,0.0,1.0,1.0,1.0
2,1.020000,0.000000,0.000000,92.000000,1.2,14.90000,48.000000,5.400000,2.0,1.0,1.0,1.0
3,1.010000,2.000000,3.000000,423.000000,1.8,9.60000,31.000000,3.742738,2.0,1.0,2.0,3.0
4,1.005000,4.000000,0.000000,117.000000,3.8,11.20000,32.000000,3.900000,2.0,2.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
395,1.020000,0.000000,0.000000,91.000000,0.7,14.00000,46.000000,5.800000,2.0,1.0,1.0,1.0
396,1.015000,3.000000,2.000000,463.000000,2.8,12.20000,40.000000,4.600000,0.0,2.0,2.0,1.0
397,1.010512,2.699747,-0.255426,103.000000,5.3,6.30000,19.000000,2.600000,0.0,2.0,1.0,3.0
398,1.015000,3.000000,0.000000,106.000000,15.2,8.60000,26.000000,2.500000,1.0,2.0,1.0,1.0
399,1.020000,0.000000,0.000000,119.000000,0.7,14.11269,43.142595,5.029438,2.0,1.0,1.0,1.0

In [25]:
y=df['Label']

In [26]:
a=pd.concat([x,y],axis=1)

In [27]:
a

,sg,al,su,bgr,sc,hemo,pcv,rbcc,rbc,htn,dm,appet,Label
0,1.020000,1.000000,0.000000,121.000000,1.2,15.40000,44.000000,5.200000,0.0,2.0,2.0,1.0,ckd
1,1.020000,4.000000,0.000000,155.893755,0.8,11.30000,38.000000,4.483714,0.0,1.0,1.0,1.0,ckd
2,1.020000,0.000000,0.000000,92.000000,1.2,14.90000,48.000000,5.400000,2.0,1.0,1.0,1.0,notckd
3,1.010000,2.000000,3.000000,423.000000,1.8,9.60000,31.000000,3.742738,2.0,1.0,2.0,3.0,ckd
4,1.005000,4.000000,0.000000,117.000000,3.8,11.20000,32.000000,3.900000,2.0,2.0,1.0,3.0,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,1.020000,0.000000,0.000000,91.000000,0.7,14.00000,46.000000,5.800000,2.0,1.0,1.0,1.0,notckd
396,1.015000,3.000000,2.000000,463.000000,2.8,12.20000,40.000000,4.600000,0.0,2.0,2.0,1.0,ckd
397,1.010512,2.699747,-0.255426,103.000000,5.3,6.30000,19.000000,2.600000,0.0,2.0,1.0,3.0,ckd
398,1.015000,3.000000,0.000000,106.000000,15.2,8.60000,26.000000,2.500000,1.0,2.0,1.0,1.0,ckd
399,1.020000,0.000000,0.000000,119.000000,0.7,14.11269,43.142595,5.029438,2.0,1.0,1.0,1.0,notckd

In [28]:
#a=a.sort_values(['bu'],ascending=False)
#a.reset_index(drop=True,inplace=True)

In [29]:
#a.tail(40)

In [30]:
Label={'notckd':0,'ckd':1}
a['Label']=a['Label'].map(Label)

In [31]:
a.head(20)

,sg,al,su,bgr,sc,hemo,pcv,rbcc,rbc,htn,dm,appet,Label
0,1.020,1.0,0.0,121.000000,1.2,15.4,44.0,5.200000,0.0,2.0,2.0,1.0,1
1,1.020,4.0,0.0,155.893755,0.8,11.3,38.0,4.483714,0.0,1.0,1.0,1.0,1
2,1.020,0.0,0.0,92.000000,1.2,14.9,48.0,5.400000,2.0,1.0,1.0,1.0,0
3,1.010,2.0,3.0,423.000000,1.8,9.6,31.0,3.742738,2.0,1.0,2.0,3.0,1
4,1.005,4.0,0.0,117.000000,3.8,11.2,32.0,3.900000,2.0,2.0,1.0,3.0,1
5,1.020,0.0,0.0,89.000000,0.5,16.7,52.0,5.000000,2.0,1.0,1.0,1.0,0
6,1.010,2.0,0.0,106.000000,1.4,11.6,35.0,4.600000,2.0,1.0,1.0,1.0,1
7,1.015,3.0,0.0,74.000000,1.1,12.2,39.0,4.400000,0.0,2.0,2.0,1.0,1
8,1.025,0.0,0.0,124.000000,1.0,14.9,41.0,5.700000,2.0,1.0,1.0,1.0,0
9,1.020,0.0,0.0,110.000000,0.7,14.3,40.0,5.800000,2.0,1.0,1.0,0.0,0
10,1.020,0.0,0.0,122.000000,0.8,17.1,41.0,5.200000,2.0,1.0,1.0,1.0,0
11,1.020,2.0,0.0,70.000000,7.2,9.5,29.0,3.700000,1.0,2.0,2.0,3.0,1
12,1.010,2.0,4.0,490.000000,4.0,9.4,28.0,3.561102,0.0,2.0,2.0,1.0,1
13,1.020,0.0,0.0,128.000000,1.2,15.2,52.0,5.700000,2.0,1.0,1.0,1.0,0
14,1.020,0.0,0.0,137.000000,0.5,13.6,44.0,4.500000,2.0,1.0,1.0,1.0,0
15,1.020,0.0,0.0,102.000000,0.7,13.2,44.0,5.400000,2.0,1.0,1.0,1.0,0
16,1.025,0.0,0.0,132.000000,1.1,13.7,45.0,5.600000,2.0,1.0,1.0,1.0,0
17,1.010,0.0,0.0,100.000000,24.0,12.4,36.0,4.152490,0.0,1.0,1.0,1.0,1
18,1.015,2.0,4.0,410.000000,1.1,12.4,44.0,5.000000,2.0,1.0,2.0,1.0,1
19,1.025,0.0,0.0,75.000000,0.8,16.8,51.0,6.500000,2.0,1.0,1.0,1.0,0

In [32]:
u=a.iloc[:,:-1]
v=a['Label']

# SMOTE Technique

In [33]:
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import SVMSMOTE

In [34]:
smote=SMOTE()
sm = SVMSMOTE()

In [35]:
x_train_resample,y_train_resample=sm.fit_resample(u,v)

In [36]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
k=scaler.fit_transform(x_train_resample)

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(k,y_train_resample,test_size=0.2, random_state=0)

In [38]:
from sklearn.model_selection import ShuffleSplit
fold=ShuffleSplit(n_splits=5, test_size=0.1, random_state=0)
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RandomizedSearchCV

# Support Vector Machine

In [46]:
from sklearn.svm import SVC
svm=SVC()
param_grid={'C':[0.1,1,10,100],'gamma':[0.01,0.1,1,10,100],'kernel':['rbf']}
svm_randomgrid=RandomizedSearchCV(estimator=svm,param_distributions=param_grid,verbose=1,n_jobs=-1,cv=fold)
svm_randomgrid.fit(x_train,y_train)
svm_randomgrid.best_estimator_, svm_randomgrid.best_score_

Fitting 5 folds for each of 10 candidates, totalling 50 fits

(SVC(C=10, gamma=0.01), 1.0)

# K-Nearest Neighbors

In [40]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
param_grid={'n_neighbors':range(1, 21, 2),
            'weights':['uniform', 'distance'],
            'metric':['euclidean', 'manhattan', 'minkowski']}
knn_randomgrid=RandomizedSearchCV(estimator=knn,param_distributions=param_grid,verbose=4,n_jobs=6,cv=fold)
knn_randomgrid.fit(x_train,y_train)
knn_randomgrid.best_params_, knn_randomgrid.best_score_

Fitting 5 folds for each of 10 candidates, totalling 50 fits

({'weights': 'distance', 'n_neighbors': 7, 'metric': 'manhattan'}, 1.0)

# Random Forest

In [41]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
n_estimators=[50,60,70,80,90,100,150,200,250,300,400]
max_features=['auto']
bootstrap=[True,False]
min_samples_split=[2, 3,4,5,6,7,8]
min_samples_leaf=[1,2,3,5]
max_depth=[None]
param_grid={'n_estimators':n_estimators,
            'max_features':max_features,
            'bootstrap':bootstrap,
            'min_samples_split':min_samples_split,
            'min_samples_leaf':min_samples_leaf,
            'max_depth':max_depth}
print(param_grid)
rf_randomgrid=RandomizedSearchCV(estimator=rf,param_distributions=param_grid,verbose=1,n_jobs=-1,cv=fold)
rf_randomgrid.fit(x_train,y_train)
rf_randomgrid.best_params_, rf_randomgrid.best_score_

{'n_estimators': [50, 60, 70, 80, 90, 100, 150, 200, 250, 300, 400], 'max_features': ['auto'], 'bootstrap': [True, False], 'min_samples_split': [2, 3, 4, 5, 6, 7, 8], 'min_samples_leaf': [1, 2, 3, 5], 'max_depth': [None]}
Fitting 5 folds for each of 10 candidates, totalling 50 fits

({'n_estimators': 70,
  'min_samples_split': 8,
  'min_samples_leaf': 3,
  'max_features': 'auto',
  'max_depth': None,
  'bootstrap': True},
 1.0)

# Decision tree

In [47]:
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier()
param_grid={'criterion':['gini','entropy'],
            'max_depth':[1,2,None],
            'min_samples_split':[2,3,4,5,6,7]}
print(param_grid)
tree_randomgrid=RandomizedSearchCV(estimator=tree,param_distributions=param_grid,verbose=True,n_jobs=-1,cv=fold)
tree_randomgrid.fit(x_train,y_train)
tree_randomgrid.best_params_, tree_randomgrid.best_score_

{'criterion': ['gini', 'entropy'], 'max_depth': [1, 2, None], 'min_samples_split': [2, 3, 4, 5, 6, 7]}
Fitting 5 folds for each of 10 candidates, totalling 50 fits

({'min_samples_split': 6, 'max_depth': None, 'criterion': 'entropy'}, 1.0)

# Gradient Boosting

In [43]:
from sklearn.ensemble import GradientBoostingClassifier
gdb=GradientBoostingClassifier()
param_grid={'learning_rate':[0.01,0.05,0.1],
            'n_estimators':[100,200,300,400,500],
            'max_depth':[2,3,4,5,6,7,8],
            'min_samples_leaf':[4,8,10]}
gdb_randomgrid=RandomizedSearchCV(estimator=gdb,param_distributions=param_grid,verbose=1,n_jobs=-1,cv=fold)
gdb_randomgrid.fit(x_train,y_train)
gdb_randomgrid.best_params_, gdb_randomgrid.best_score_

Fitting 5 folds for each of 10 candidates, totalling 50 fits

({'n_estimators': 500,
  'min_samples_leaf': 10,
  'max_depth': 6,
  'learning_rate': 0.05},
 1.0)

# LightGBM

In [44]:
from lightgbm import LGBMClassifier
lgb=LGBMClassifier()
param_grid={'learning_rate':[0.05,0.1],
            'n_estimators':[100,200,300,400,500],
            'max_depth':[2,3,4,5,6,7,8,9,10],
            'min_child_weight':[1,3,5,7,9]}
lgb_randomgrid=RandomizedSearchCV(estimator=lgb,param_distributions=param_grid,verbose=True,n_jobs=4,cv=fold)
lgb_randomgrid.fit(x_train,y_train)
lgb_randomgrid.best_params_, lgb_randomgrid.best_score_

Fitting 5 folds for each of 10 candidates, totalling 50 fits

({'n_estimators': 300,
  'min_child_weight': 5,
  'max_depth': 3,
  'learning_rate': 0.05},
 0.9949999999999999)

# XgBoost

In [45]:
from xgboost import XGBClassifier
xgb=XGBClassifier()
param_grid={'learning_rate':[0.05,0.1,0.15,0.2,0.25],
            'n_estimators':[100,200,300,400,500,600,700],
            'max_depth':[2,3,4,5,6,7,8,9,10],
            'min_child_weight':[1,2,3,4,5,6,7,8,9],
            'eval_metric':['error']}
xgb_randomgrid=RandomizedSearchCV(estimator=xgb,param_distributions=param_grid,verbose=True,n_jobs=4,cv=fold)
xgb_randomgrid.fit(x_train,y_train)
xgb_randomgrid.best_params_, xgb_randomgrid.best_score_

Fitting 5 folds for each of 10 candidates, totalling 50 fits

C:\Users\MD SABBIR SK\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

({'n_estimators': 700,
  'min_child_weight': 8,
  'max_depth': 4,
  'learning_rate': 0.25,
  'eval_metric': 'error'},
 0.9949999999999999)